name: Create Installers

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version String'     
        required: true

jobs:
  create-installers:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Install mingw-w64
        run: sudo apt-get install mingw-w64
      
      - name: Install nfpm
        run: |
          echo 'deb [trusted=yes] https://repo.goreleaser.com/apt/ /' | sudo tee /etc/apt/sources.list.d/goreleaser.list
          sudo apt update
          sudo apt install nfpm
        
      - name: Replace VERSION_STRING in nfpm configuration file with parameter
        run: |
          cd nfpm
          sed -i 's/VERSION_STRING/${{ github.event.inputs.version }}/g' nfpm.yaml
          cd ..

      - name: Generate *.deb/*.rmp installer files
        run: |
          cd nfpm
          ./generateInstallers.sh
          cd ..    
          
      - name: Archive debian installer
        uses: actions/upload-artifact@v2
        with:
          name: debian-installer
          path: memeassembly_${{ github.event.inputs.version }}_amd64.deb
          
      - name: Archive rpm installer
        uses: actions/upload-artifact@v2
        with:
          name: rpm-installer
          path: memeassembly-${{ github.event.inputs.version }}.x86_64.rpm

      - name: Compile for Windows
        run: make windows

      - name: Upload Windows executable
        uses: actions/upload-artifact@v2
        with:
          name: memeasm.exe
          path: memeasm.exe